# -*- coding: utf-8 -*-
"""RV-Exp_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ya9FtjDsPc_JpQAWEFov7PY6bh3cZHwm
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

# Upload your image in Google Colab
from google.colab import files
uploaded = files.upload()

# Read the image
img = cv2.imread(list(uploaded.keys())[0], cv2.IMREAD_COLOR)

# Convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Histogram Equalization
equalized_img = cv2.equalizeHist(gray)

# Display the original and equalized images
plt.figure(figsize=(10, 5))

# Original Image
plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title("Original Grayscale Image")
plt.axis("off")

# Equalized Image
plt.subplot(1, 2, 2)
plt.imshow(equalized_img, cmap='gray')
plt.title("Equalized Image")
plt.axis("off")

plt.show()

import cv2

# Upload video
uploaded = files.upload()

# Load the video
cap = cv2.VideoCapture(list(uploaded.keys())[0])

# Read the video frame by frame
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Split the video into its color channels
    b, g, r = cv2.split(frame)

    # Manipulate the channels (For example, increase the red channel intensity)
    r = cv2.add(r, 50)  # Increase red channel brightness

    # Merge the manipulated channels back
    manipulated_frame = cv2.merge([b, g, r])

    # Display the manipulated frame
    cv2_imshow(manipulated_frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

import cv2

# Upload video
uploaded = files.upload()

# Load the video
cap = cv2.VideoCapture(list(uploaded.keys())[0])

# Initialize the previous frame variable
ret, prev_frame = cap.read()

# Convert the previous frame to grayscale
prev_gray = cv2.cvtColor(prev_frame, cv2.COLOR_BGR2GRAY)

while cap.isOpened():
    ret, current_frame = cap.read()
    if not ret:
        break

    # Convert the current frame to grayscale
    current_gray = cv2.cvtColor(current_frame, cv2.COLOR_BGR2GRAY)

    # Compute the absolute difference between the previous and current frame
    frame_diff = cv2.absdiff(prev_gray, current_gray)

    # Threshold the difference to highlight significant changes
    _, thresh_diff = cv2.threshold(frame_diff, 25, 255, cv2.THRESH_BINARY)

    # Display the frame difference
    cv2_imshow(thresh_diff)

    # Update the previous frame
    prev_gray = current_gray

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

