# -*- coding: utf-8 -*-
"""RV_EXP-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jilU5VUMdxy7yKzvYD35wVY3lgCCB1uQ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# --- Step 1: Provide image path ---
image_path = '/content/img_RV.jpg'

# --- Step 2: Load and preprocess ---
img = cv2.imread(image_path)
if img is None:
  raise ValueError(f"Could not load image: {image_path}")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Gradient (Sobel)
grad_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
grad_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
gradient = cv2.magnitude(grad_x, grad_y)
gradient = cv2.normalize(gradient, None, 0, 255,
cv2.NORM_MINMAX).astype(np.uint8)

# Edge (Canny)
edges = cv2.Canny(gray, 50, 150, apertureSize=3)

# --- Step 3: Standard Hough Transform ---
lines = cv2.HoughLines(edges, 1, np.pi / 180, 80) # lowered threshold
img_lines = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

if lines is not None:
  for line in lines:
    rho, theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho

    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(img_lines, (x1, y1), (x2, y2), (255, 0, 255), 2)

# --- Optional: Probabilistic Hough Transform ---
lines_p = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=50,
minLineLength=50, maxLineGap=10)
img_lines_p = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
if lines_p is not None:
  for x1, y1, x2, y2 in lines_p[:, 0]:
    cv2.line(img_lines_p, (x1, y1), (x2, y2), (0, 0, 255), 2)

# --- Step 4: Compute parameter space (ρ, θ) manually ---
thetas = np.deg2rad(np.arange(-90.0, 90.0))
height, width = edges.shape
diag_len = int(np.ceil(np.sqrt(width ** 2 + height ** 2)))
rhos = np.linspace(-diag_len, diag_len, diag_len * 2)
accumulator = np.zeros((2 * diag_len, len(thetas)), dtype=np.uint64)

y_idxs, x_idxs = np.nonzero(edges)
for i in range(len(x_idxs)):
  x = x_idxs[i]
  y = y_idxs[i]
  for t_idx in range(len(thetas)):
    rho_val = x * np.cos(thetas[t_idx]) + y * np.sin(thetas[t_idx])
    rho_idx = int(np.round(rho_val + diag_len))
    accumulator[rho_idx, t_idx] += 1

# --- Step 5: Visualization layout ---
fig = plt.figure(figsize=(16, 10))
fig.suptitle("Line Detection Results", fontsize=20, color='yellow')

# Original
plt.subplot(2, 3, 1)
plt.title("Original Image")
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')

# Gradient
plt.subplot(2, 3, 2)
plt.title("Gradient")
plt.imshow(gradient, cmap='gray')
plt.axis('off')

# Edge
plt.subplot(2, 3, 3)
plt.title("Edge (Canny)")
plt.imshow(edges, cmap='gray')
plt.axis('off')

# Hough Transform
plt.subplot(2, 3, 4)
plt.title(r"Hough Transform $A(\rho, \theta)$", fontsize=12)
plt.imshow(
  accumulator,
  cmap='hot',
  extent=[np.rad2deg(thetas[0]), np.rad2deg(thetas[-1]), rhos[0], rhos[-1]],
  aspect='auto',
  origin='lower'
)

plt.xlabel("θ (°)", fontsize=10)
plt.ylabel("ρ (px)", fontsize=10)
plt.tick_params(axis='both', which='major', labelsize=8)

# Standard Hough Lines
plt.subplot(2, 3, 5)
plt.title("Detected Lines (Standard)")
plt.imshow(cv2.cvtColor(img_lines, cv2.COLOR_BGR2RGB))
plt.axis('off')

import cv2
import numpy as np
import matplotlib.pyplot as plt

# --- Step 1: Provide the image path ---
image_path = '/content/img_RV_exp-7.png'  # Ensure you have the correct path to your image

# --- Step 2: Load and preprocess the image ---
img = cv2.imread(image_path)
if img is None:
    raise ValueError(f"Could not load image: {image_path}")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convert to grayscale

# Apply GaussianBlur to reduce noise (Optional but helps)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# --- Step 3: Compute the gradient (Sobel) ---
grad_x = cv2.Sobel(blurred, cv2.CV_64F, 1, 0, ksize=3)  # Gradient in X direction
grad_y = cv2.Sobel(blurred, cv2.CV_64F, 0, 1, ksize=3)  # Gradient in Y direction
gradient = cv2.magnitude(grad_x, grad_y)
gradient = cv2.normalize(gradient, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

# --- Step 4: Edge detection using Canny ---
edges = cv2.Canny(gradient, 50, 150, apertureSize=3)

# --- Step 5: Standard Hough Transform ---
lines = cv2.HoughLines(edges, 1, np.pi / 180, 100)  # Standard Hough Lines
img_lines = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

if lines is not None:
    for line in lines:
        rho, theta = line[0]
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a * rho
        y0 = b * rho
        x1 = int(x0 + 1000 * (-b))
        y1 = int(y0 + 1000 * (a))
        x2 = int(x0 - 1000 * (-b))
        y2 = int(y0 - 1000 * (a))
        cv2.line(img_lines, (x1, y1), (x2, y2), (255, 0, 255), 2)  # Draw in magenta

# --- Step 6: Probabilistic Hough Transform ---
lines_p = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=50, minLineLength=50, maxLineGap=10)
img_lines_p = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

if lines_p is not None:
    for x1, y1, x2, y2 in lines_p[:, 0]:
        cv2.line(img_lines_p, (x1, y1), (x2, y2), (0, 0, 255), 2)  # Draw in red

# --- Step 7: Hough Space Calculation (ρ, θ) ---
thetas = np.deg2rad(np.arange(-90.0, 90.0))  # Theta range from -90 to 90 degrees
height, width = edges.shape
diag_len = int(np.ceil(np.sqrt(width ** 2 + height ** 2)))  # Diagonal length
rhos = np.linspace(-diag_len, diag_len, diag_len * 2)  # Range of ρ
accumulator = np.zeros((2 * diag_len, len(thetas)), dtype=np.uint64)  # Accumulator array

# Accumulate votes for each edge point in Hough space
y_idxs, x_idxs = np.nonzero(edges)
for i in range(len(x_idxs)):
    x = x_idxs[i]
    y = y_idxs[i]
    for t_idx in range(len(thetas)):
        rho_val = x * np.cos(thetas[t_idx]) + y * np.sin(thetas[t_idx])
        rho_idx = int(np.round(rho_val + diag_len))
        accumulator[rho_idx, t_idx] += 1

# --- Step 8: Visualization ---
fig, ax = plt.subplots(2, 3, figsize=(16, 10))

# Original image
ax[0, 0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
ax[0, 0].set_title("Original Image")
ax[0, 0].axis('off')

# Gradient image
ax[0, 1].imshow(gradient, cmap='gray')
ax[0, 1].set_title("Gradient Magnitude")
ax[0, 1].axis('off')

# Edge-detected image (Canny)
ax[0, 2].imshow(edges, cmap='gray')
ax[0, 2].set_title("Edge Detection (Canny)")
ax[0, 2].axis('off')

# Hough Transform Accumulator Space
ax[1, 0].imshow(
    accumulator,
    cmap='hot',
    extent=[np.rad2deg(thetas[0]), np.rad2deg(thetas[-1]), rhos[0], rhos[-1]],
    aspect='auto',
    origin='lower'
)
ax[1, 0].set_title(r'Hough Transform $A(\rho, \theta)$')
ax[1, 0].set_xlabel("θ (degrees)")
ax[1, 0].set_ylabel("ρ (px)")
ax[1, 0].tick_params(axis='both', which='major', labelsize=8)

# Detected Lines (Standard Hough Transform)
ax[1, 1].imshow(cv2.cvtColor(img_lines, cv2.COLOR_BGR2RGB))
ax[1, 1].set_title("Detected Lines (Standard)")
ax[1, 1].axis('off')

# Detected Lines (Probabilistic Hough Transform)
ax[1, 2].imshow(cv2.cvtColor(img_lines_p, cv2.COLOR_BGR2RGB))
ax[1, 2].set_title("Detected Lines (Probabilistic)")
ax[1, 2].axis('off')

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# --- Step 1: Provide the image path ---
image_path = '/content/img_RV.jpg'  # Ensure you have the correct path to your image

# --- Step 2: Load and preprocess the image ---
img = cv2.imread(image_path)
if img is None:
    raise ValueError(f"Could not load image: {image_path}")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convert to grayscale

# Apply GaussianBlur to reduce noise (Optional but helps)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# --- Step 3: Compute the gradient (Sobel) ---
grad_x = cv2.Sobel(blurred, cv2.CV_64F, 1, 0, ksize=3)  # Gradient in X direction
grad_y = cv2.Sobel(blurred, cv2.CV_64F, 0, 1, ksize=3)  # Gradient in Y direction
gradient = cv2.magnitude(grad_x, grad_y)
gradient = cv2.normalize(gradient, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

# --- Step 4: Edge detection using Canny ---
edges = cv2.Canny(gradient, 50, 150, apertureSize=3)

# --- Step 5: Standard Hough Transform ---
lines = cv2.HoughLines(edges, 1, np.pi / 180, 100)  # Standard Hough Lines
img_lines = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

if lines is not None:
    for line in lines:
        rho, theta = line[0]
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a * rho
        y0 = b * rho
        x1 = int(x0 + 1000 * (-b))
        y1 = int(y0 + 1000 * (a))
        x2 = int(x0 - 1000 * (-b))
        y2 = int(y0 - 1000 * (a))
        cv2.line(img_lines, (x1, y1), (x2, y2), (255, 0, 255), 2)  # Draw in magenta

# --- Step 6: Probabilistic Hough Transform ---
lines_p = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=50, minLineLength=50, maxLineGap=10)
img_lines_p = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

if lines_p is not None:
    for x1, y1, x2, y2 in lines_p[:, 0]:
        cv2.line(img_lines_p, (x1, y1), (x2, y2), (0, 0, 255), 2)  # Draw in red

# --- Step 7: Hough Space Calculation (ρ, θ) ---
thetas = np.deg2rad(np.arange(-90.0, 90.0))  # Theta range from -90 to 90 degrees
height, width = edges.shape
diag_len = int(np.ceil(np.sqrt(width ** 2 + height ** 2)))  # Diagonal length
rhos = np.linspace(-diag_len, diag_len, diag_len * 2)  # Range of ρ
accumulator = np.zeros((2 * diag_len, len(thetas)), dtype=np.uint64)  # Accumulator array

# Accumulate votes for each edge point in Hough space
y_idxs, x_idxs = np.nonzero(edges)
for i in range(len(x_idxs)):
    x = x_idxs[i]
    y = y_idxs[i]
    for t_idx in range(len(thetas)):
        rho_val = x * np.cos(thetas[t_idx]) + y * np.sin(thetas[t_idx])
        rho_idx = int(np.round(rho_val + diag_len))
        accumulator[rho_idx, t_idx] += 1

# --- Step 8: Visualization ---
fig, ax = plt.subplots(2, 3, figsize=(16, 10))

# Original image
ax[0, 0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
ax[0, 0].set_title("Original Image")
ax[0, 0].axis('off')

# Gradient image
ax[0, 1].imshow(gradient, cmap='gray')
ax[0, 1].set_title("Gradient Magnitude")
ax[0, 1].axis('off')

# Edge-detected image (Canny)
ax[0, 2].imshow(edges, cmap='gray')
ax[0, 2].set_title("Edge Detection (Canny)")
ax[0, 2].axis('off')

# Hough Transform Accumulator Space
ax[1, 0].imshow(
    accumulator,
    cmap='hot',
    extent=[np.rad2deg(thetas[0]), np.rad2deg(thetas[-1]), rhos[0], rhos[-1]],
    aspect='auto',
    origin='lower'
)
ax[1, 0].set_title(r'Hough Transform $A(\rho, \theta)$')
ax[1, 0].set_xlabel("θ (degrees)")
ax[1, 0].set_ylabel("ρ (px)")
ax[1, 0].tick_params(axis='both', which='major', labelsize=8)

# Detected Lines (Standard Hough Transform)
ax[1, 1].imshow(cv2.cvtColor(img_lines, cv2.COLOR_BGR2RGB))
ax[1, 1].set_title("Detected Lines (Standard)")
ax[1, 1].axis('off')

# Detected Lines (Probabilistic Hough Transform)
ax[1, 2].imshow(cv2.cvtColor(img_lines_p, cv2.COLOR_BGR2RGB))
ax[1, 2].set_title("Detected Lines (Probabilistic)")
ax[1, 2].axis('off')

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# --- Step 1: Provide image path ---
image_path = '/content/img_RV_exp-7.png'

# --- Step 2: Load and preprocess ---
img = cv2.imread(image_path)
if img is None:
  raise ValueError(f"Could not load image: {image_path}")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Gradient (Sobel)
grad_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
grad_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
gradient = cv2.magnitude(grad_x, grad_y)
gradient = cv2.normalize(gradient, None, 0, 255,
cv2.NORM_MINMAX).astype(np.uint8)

# Edge (Canny)
edges = cv2.Canny(gray, 50, 150, apertureSize=3)

# --- Step 3: Standard Hough Transform ---
lines = cv2.HoughLines(edges, 1, np.pi / 180, 80) # lowered threshold
img_lines = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

if lines is not None:
  for line in lines:
    rho, theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho

    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(img_lines, (x1, y1), (x2, y2), (255, 0, 255), 2)

# --- Optional: Probabilistic Hough Transform ---
lines_p = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=50,
minLineLength=50, maxLineGap=10)
img_lines_p = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
if lines_p is not None:
  for x1, y1, x2, y2 in lines_p[:, 0]:
    cv2.line(img_lines_p, (x1, y1), (x2, y2), (0, 0, 255), 2)

# --- Step 4: Compute parameter space (ρ, θ) manually ---
thetas = np.deg2rad(np.arange(-90.0, 90.0))
height, width = edges.shape
diag_len = int(np.ceil(np.sqrt(width ** 2 + height ** 2)))
rhos = np.linspace(-diag_len, diag_len, diag_len * 2)
accumulator = np.zeros((2 * diag_len, len(thetas)), dtype=np.uint64)

y_idxs, x_idxs = np.nonzero(edges)
for i in range(len(x_idxs)):
  x = x_idxs[i]
  y = y_idxs[i]
  for t_idx in range(len(thetas)):
    rho_val = x * np.cos(thetas[t_idx]) + y * np.sin(thetas[t_idx])
    rho_idx = int(np.round(rho_val + diag_len))
    accumulator[rho_idx, t_idx] += 1

# --- Step 5: Visualization layout ---
fig = plt.figure(figsize=(16, 10))
fig.suptitle("Line Detection Results", fontsize=20, color='yellow')

# Original
plt.subplot(2, 3, 1)
plt.title("Original Image")
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')

# Gradient
plt.subplot(2, 3, 2)
plt.title("Gradient")
plt.imshow(gradient, cmap='gray')
plt.axis('off')

# Edge
plt.subplot(2, 3, 3)
plt.title("Edge (Canny)")
plt.imshow(edges, cmap='gray')
plt.axis('off')

# Hough Transform
plt.subplot(2, 3, 4)
plt.title(r"Hough Transform $A(\rho, \theta)$", fontsize=12)
plt.imshow(
  accumulator,
  cmap='hot',
  extent=[np.rad2deg(thetas[0]), np.rad2deg(thetas[-1]), rhos[0], rhos[-1]],
  aspect='auto',
  origin='lower'
)

plt.xlabel("θ (°)", fontsize=10)
plt.ylabel("ρ (px)", fontsize=10)
plt.tick_params(axis='both', which='major', labelsize=8)

# Standard Hough Lines
plt.subplot(2, 3, 5)
plt.title("Detected Lines (Standard)")
plt.imshow(cv2.cvtColor(img_lines, cv2.COLOR_BGR2RGB))
plt.axis('off')