# -*- coding: utf-8 -*-
"""Exp-6(RV)  11/11/25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBhW-qPOd4tcqF5j8UDm8_qGmfeUetUO
"""

# Edge Detection using First & Second Order Derivatives
# Includes: Sobel, Scharr, Prewitt, Roberts, Gradient, Laplacian

import cv2
import numpy as np
import matplotlib.pyplot as plt

# 1. Load Image
img = cv2.imread('/content/people.jpg')
if img is None:
    raise ValueError("Image not found! Replace with your own path or upload an image.")

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


# 2. FIRST-ORDER DERIVATIVES

# (a) Sobel Operator
sobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
sobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
sobel_mag = cv2.magnitude(sobelx, sobely)

# (b) Scharr Operator
scharrx = cv2.Scharr(gray, cv2.CV_64F, 1, 0)
scharry = cv2.Scharr(gray, cv2.CV_64F, 0, 1)
scharr_mag = cv2.magnitude(scharrx, scharry)

# (c) Prewitt Operator (manual kernel)
kernelx = np.array([[-1, 0, 1],
                    [-1, 0, 1],
                    [-1, 0, 1]], dtype=np.float32)
kernely = np.array([[1, 1, 1],
                    [0, 0, 0],
                    [-1, -1, -1]], dtype=np.float32)
prewittx = cv2.filter2D(gray, -1, kernelx)
prewitty = cv2.filter2D(gray, -1, kernely)
prewitt_mag = cv2.magnitude(prewittx.astype(float), prewitty.astype(float))

# (d) Roberts Cross Operator (2x2 kernels)
roberts_cross_v = np.array([[1, 0],
                            [0, -1]], dtype=np.float32)
roberts_cross_h = np.array([[0, 1],
                            [-1, 0]], dtype=np.float32)
robertsx = cv2.filter2D(gray, cv2.CV_64F, roberts_cross_v)
robertsy = cv2.filter2D(gray, cv2.CV_64F, roberts_cross_h)
roberts_mag = cv2.magnitude(robertsx, robertsy)

# (e) Morphological Gradient (Dilation - Erosion)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
gradient = cv2.morphologyEx(gray, cv2.MORPH_GRADIENT, kernel)


# 3. SECOND-ORDER DERIVATIVE
laplacian = cv2.Laplacian(gray, cv2.CV_64F, ksize=3)
laplacian_abs = cv2.convertScaleAbs(laplacian)


# 4. Visualization
titles = [
    'Original (RGB)',
    'Grayscale',
    'Sobel (1st)',
    'Scharr (1st)',
    'Prewitt (1st)',
    'Roberts (1st)',
    'Morphological Gradient (1st)',
    'Laplacian (2nd)'
]
images = [
    img_rgb, gray, sobel_mag, scharr_mag,
    prewitt_mag, roberts_mag, gradient, laplacian_abs
]

plt.figure(figsize=(15, 10))
for i in range(len(images)):
    plt.subplot(2, 4, i + 1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis('off')

plt.tight_layout()
plt.show()