# -*- coding: utf-8 -*-
"""RV_Exp_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yz7b-CCHQbbEDITRLMxzYZEQts-X4-Kf
"""

# Install OpenCV
!pip install opencv-python

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload an image
print("Upload an image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Read and convert to RGB for display
image = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Show original image
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis('off')
plt.show()

# ✅ 1. Translation
rows, cols = image.shape[:2]
tx, ty = 100, 50  # shift in x and y
translation_matrix = np.float32([[1, 0, tx], [0, 1, ty]])
translated_img = cv2.warpAffine(image_rgb, translation_matrix, (cols + tx, rows + ty))

plt.imshow(translated_img)
plt.title("Translated Image")
plt.axis('off')
plt.show()

# ✅ 2. Scaling (Resize)
scaled_img = cv2.resize(image_rgb, None, fx=1.5, fy=1.5, interpolation=cv2.INTER_LINEAR)
plt.imshow(scaled_img)
plt.title("Scaled Image (1.5x)")
plt.axis('off')
plt.show()

# ✅ 3. Rotation
center = (cols // 2, rows // 2)
angle = 45
scale = 1
rotation_matrix = cv2.getRotationMatrix2D(center, angle, scale)
rotated_img = cv2.warpAffine(image_rgb, rotation_matrix, (cols, rows))

plt.imshow(rotated_img)
plt.title("Rotated Image (45°)")
plt.axis('off')
plt.show()

# ✅ 4. Grayscale
gray_img = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY)
plt.imshow(gray_img, cmap='gray')
plt.title("Grayscale Image")
plt.axis('off')
plt.show()

print("Upload a video:")
uploaded_video = files.upload()
video_path = list(uploaded_video.keys())[0]

cap = cv2.VideoCapture(video_path)
frame_count = 0

while True:
    ret, frame = cap.read()
    if not ret or frame_count > 50:  # limit to 50 frames for demo
        break

    # Convert to RGB for display
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # ✅ 1. Grayscale
    gray_frame = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2GRAY)

    # ✅ 2. Gaussian Blur
    blur_frame = cv2.GaussianBlur(frame_rgb, (7, 7), 0)

    # ✅ 3. Edge Detection
    edges_frame = cv2.Canny(frame, 100, 200)

    # Display Original and Processed Frames
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 4, 1)
    plt.imshow(frame_rgb)
    plt.title("Original")
    plt.axis('off')

    plt.subplot(1, 4, 2)
    plt.imshow(gray_frame, cmap='gray')
    plt.title("Grayscale")
    plt.axis('off')

    plt.subplot(1, 4, 3)
    plt.imshow(blur_frame)
    plt.title("Blurred")
    plt.axis('off')

    plt.subplot(1, 4, 4)
    plt.imshow(edges_frame, cmap='gray')
    plt.title("Edges")
    plt.axis('off')

    plt.show()

    frame_count += 1

cap.release()