# -*- coding: utf-8 -*-
"""RV_Exp_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASP_MvxkdLBvBk0VJD5Y8GM0zEcOKBzs
"""

# Install OpenCV
!pip install opencv-python

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# ✅ 1. Upload Image
print("Upload an image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Read image in BGR format
image = cv2.imread(image_path)

# Convert BGR to RGB for displaying in Matplotlib
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Display Original Image
plt.imshow(image_rgb)
plt.title('Original Image')
plt.axis('off')
plt.show()

# ✅ 2. Apply Negative
negative_image = 255 - image_rgb
plt.imshow(negative_image)
plt.title('Negative Image')
plt.axis('off')
plt.show()

# ✅ 3. Adjust Brightness
brightness_value = 50
bright_image = cv2.convertScaleAbs(image_rgb, alpha=1, beta=brightness_value)
plt.imshow(bright_image)
plt.title('Brightness Increased')
plt.axis('off')
plt.show()

# ✅ 4. Adjust Contrast
contrast_value = 1.5
contrast_image = cv2.convertScaleAbs(image_rgb, alpha=contrast_value, beta=0)
plt.imshow(contrast_image)
plt.title('Contrast Increased')
plt.axis('off')
plt.show()

# ✅ 5. Save Modified Image
cv2.imwrite('contrast_image.jpg', cv2.cvtColor(contrast_image, cv2.COLOR_RGB2BGR))
print("Modified image saved as contrast_image.jpg")
files.download('contrast_image.jpg')

print("Upload a video file:")
uploaded_video = files.upload()
video_path = list(uploaded_video.keys())[0]

# Read video
cap = cv2.VideoCapture(video_path)

frame_count = 0
while True:
    ret, frame = cap.read()
    if not ret or frame_count > 100:  # Limit to first 100 frames for demo
        break

    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    plt.imshow(frame_rgb)
    plt.axis('off')
    plt.title(f'Frame {frame_count}')
    plt.show()

    frame_count += 1

cap.release()