# -*- coding: utf-8 -*-
"""Exp-8(RV) 11/11/25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqvnGg2moXQg-ZenRnWoxyZDeRGLaZI9
"""

# Morphological Operations Demo - OpenCV + Colab

import cv2
import numpy as np
import matplotlib.pyplot as plt

# 1. Load Image

img = cv2.imread('/content/img1.jpg')
if img is None:
    raise ValueError("Image not found! Replace with your own path or upload an image.")

# Convert from BGR (OpenCV default) to RGB for visualization
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# 2. Convert to Grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 3. Optional: Threshold / Binarize
_, binary = cv2.threshold(gray, 120, 255, cv2.THRESH_BINARY)

# 4. Define Structuring Element (Kernel)
kernel_size = 5
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (kernel_size, kernel_size))
# Alternatives: cv2.MORPH_ELLIPSE, cv2.MORPH_CROSS

# 5. Apply Morphological Operations
erosion = cv2.erode(binary, kernel, iterations=1)
dilation = cv2.dilate(binary, kernel, iterations=1)
opening = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)
closing = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)

# 6. Visualization
fig, axs = plt.subplots(2, 4, figsize=(12, 6))
axs = axs.ravel()

axs[0].imshow(img_rgb)
axs[0].set_title('Original')
axs[0].axis('off')

axs[1].imshow(gray, cmap='gray')
axs[1].set_title('Grayscale')
axs[1].axis('off')

axs[2].imshow(binary, cmap='gray')
axs[2].set_title('Binary')
axs[2].axis('off')

axs[3].imshow(kernel, cmap='gray')
axs[3].set_title(f'Kernel ({kernel_size}x{kernel_size})')
axs[3].axis('off')

axs[4].imshow(erosion, cmap='gray')
axs[4].set_title('Erosion')
axs[4].axis('off')

axs[5].imshow(dilation, cmap='gray')
axs[5].set_title('Dilation')
axs[5].axis('off')

axs[6].imshow(opening, cmap='gray')
axs[6].set_title('Opening')
axs[6].axis('off')

axs[7].imshow(closing, cmap='gray')
axs[7].set_title('Closing')
axs[7].axis('off')

plt.tight_layout()
plt.show()

img2 = cv2.imread('/content/img2.png')
if img2 is None:
    raise ValueError("Image not found! Replace with your own path or upload an image.")

# Convert from BGR (OpenCV default) to RGB for visualization
img2_rgb = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)

# 2. Convert to Grayscale
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 3. Optional: Threshold / Binarize
_, binary = cv2.threshold(gray2, 120, 255, cv2.THRESH_BINARY)

# 4. Define Structuring Element (Kernel)
kernel_size = 5
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (kernel_size, kernel_size))
# Alternatives: cv2.MORPH_ELLIPSE, cv2.MORPH_CROSS

# 5. Apply Morphological Operations
erosion = cv2.erode(binary, kernel, iterations=1)
dilation = cv2.dilate(binary, kernel, iterations=1)
opening = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)
closing = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)

# 6. Visualization
fig, axs = plt.subplots(2, 4, figsize=(12, 6))
axs = axs.ravel()

axs[0].imshow(img2_rgb)
axs[0].set_title('Original')
axs[0].axis('off')

axs[1].imshow(gray2, cmap='gray')
axs[1].set_title('Grayscale')
axs[1].axis('off')

axs[2].imshow(binary, cmap='gray')
axs[2].set_title('Binary')
axs[2].axis('off')

axs[3].imshow(kernel, cmap='gray')
axs[3].set_title(f'Kernel ({kernel_size}x{kernel_size})')
axs[3].axis('off')

axs[4].imshow(erosion, cmap='gray')
axs[4].set_title('Erosion')
axs[4].axis('off')

axs[5].imshow(dilation, cmap='gray')
axs[5].set_title('Dilation')
axs[5].axis('off')

axs[6].imshow(opening, cmap='gray')
axs[6].set_title('Opening')
axs[6].axis('off')

axs[7].imshow(closing, cmap='gray')
axs[7].set_title('Closing')
axs[7].axis('off')

plt.tight_layout()
plt.show()