# -*- coding: utf-8 -*-
"""RV_Exp_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jlu1c3XJndsKok85oA3IGSbtkP1_Lj5L
"""

# Install OpenCV
!pip install opencv-python

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload an image
print("Upload an image:")
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Read and convert to RGB
image = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Show Original Image
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis('off')
plt.show()

# ✅ 1. Average Filter (Smoothing)
avg_filtered = cv2.blur(image_rgb, (5, 5))
plt.imshow(avg_filtered)
plt.title("Average Filter")
plt.axis('off')
plt.show()

# ✅ 2. Gaussian Filter (Blurring)
gaussian_filtered = cv2.GaussianBlur(image_rgb, (5, 5), 0)
plt.imshow(gaussian_filtered)
plt.title("Gaussian Filter")
plt.axis('off')
plt.show()

# ✅ 3. Median Filter (Noise Reduction)
median_filtered = cv2.medianBlur(image_rgb, 5)
plt.imshow(median_filtered)
plt.title("Median Filter")
plt.axis('off')
plt.show()

# ✅ 4. Laplacian Filter (Sharpening)
gray = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY)
laplacian = cv2.Laplacian(gray, cv2.CV_64F)
laplacian = np.uint8(np.absolute(laplacian))
plt.imshow(laplacian, cmap='gray')
plt.title("Laplacian Filter (Edges)")
plt.axis('off')
plt.show()

print("Upload a video:")
uploaded_video = files.upload()
video_path = list(uploaded_video.keys())[0]

cap = cv2.VideoCapture(video_path)
frame_count = 0

while True:
    ret, frame = cap.read()
    if not ret or frame_count > 30:  # Limit to 30 frames for demo
        break

    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # ✅ Filters
    avg_filtered = cv2.blur(frame_rgb, (5, 5))
    gaussian_filtered = cv2.GaussianBlur(frame_rgb, (5, 5), 0)
    median_filtered = cv2.medianBlur(frame_rgb, 5)
    laplacian_gray = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2GRAY)
    laplacian = cv2.Laplacian(laplacian_gray, cv2.CV_64F)
    laplacian = np.uint8(np.absolute(laplacian))

    # Display Original + Filters
    plt.figure(figsize=(12, 8))

    plt.subplot(2, 3, 1)
    plt.imshow(frame_rgb)
    plt.title("Original")
    plt.axis('off')

    plt.subplot(2, 3, 2)
    plt.imshow(avg_filtered)
    plt.title("Average")
    plt.axis('off')

    plt.subplot(2, 3, 3)
    plt.imshow(gaussian_filtered)
    plt.title("Gaussian")
    plt.axis('off')

    plt.subplot(2, 3, 4)
    plt.imshow(median_filtered)
    plt.title("Median")
    plt.axis('off')

    plt.subplot(2, 3, 5)
    plt.imshow(laplacian, cmap='gray')
    plt.title("Laplacian")
    plt.axis('off')

    plt.show()

    frame_count += 1

cap.release()